plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'org.opensqz.openglass.rokid'
    compileSdk 34

    defaultConfig {
        applicationId 'org.opensqz.openglass.rokid'
        minSdk 28
        targetSdk 34
        versionCode 4
        versionName '0.1.3'

        buildConfigField 'String', 'PC_BASE_URL', '"http://127.0.0.1:18080"'
        buildConfigField 'String', 'PC_WS_URL', '"ws://127.0.0.1:18080/rokid/audio"'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
}
